name: "Build & UI Test"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  ui-test-with-fastlane:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        api-level: [22, 28, 30]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Enable Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Setup Fastlane
        run: bundle install && bundle update --local
      - name: Run Tests With Fastlane
        env:
          API: ${{matrix.api-level}}
        run: bundle exec fastlane test api:$API
